# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Zimt im Getriebe"

# URL
baseurl:            "/zimtimgetriebe"
permalink:          /:year/:title

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "About"
    href:           "//zimtimgetriebe.github.io/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
